# Even Fibonacci numbers
# Problem 2
# https://projecteuler.net/problem=2

# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values 
# do not exceed four million, find the sum of the even-valued terms.

def sum_of_even_fib(limit):
    result = 0
    num1 = 0
    num2 = 1
    while num1 < limit and num2 < limit:
        next_num = num1 + num2
        num1 = num2
        num2 = next_num
        if next_num % 2 ==0:
            result += next_num 
    return result

print(sum_of_even_fib(4000000)) # Answer = 4613732
